// This file is generated by npm run build:icons
 
export type IconName =
	| "close"
	| "edit-2-outline"
	| "eye-off"
	| "eye-outline"
	| "log-out"
	| "log-out-outline"
	| "maximize-outline"
	| "more-vertical-outline"
	| "next"
	| "play-circle-outline"
	| "plus-square-outline"
	| "search"
	| "sprite"
	| "trash-outline"
	| "checkbox-selected"
	| "vercel";
